### PR TITLE
Remove Git versioning plugin

### PR DESCRIPTION
**Pull request by iPolish**
Remove Git versioning plugin that fails to get when building with maven

### CODE REVIEW

**Comment by TheMolkaPL** [comment]
No, it gives you nice versioning.

**Comment by iPolish** [comment]
What¿?

**Comment by RainoBoy97** [comment]
versioning
n.	The use of versions as a means of distinguishing similar items.

**Comment by iPolish** [comment]
Its useless i think
Bcs i can't build without removing this.

**Comment by iPolish** [comment]
Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.0:revision (default) on project api-ocn: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

After correcting the problems, you can resume the build with the command
  mvn <goals> -rf :api-ocn

**Comment by RainoBoy97** [comment]
You're just avoiding fixing your issue by removing it.
The error clearly says why it's failing and that you're missing the `.git` directory in the `api-ocn` project.

**Pull request closed without merging**
